<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1544704132424" stop="1544704132424">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1544704132424" status="broken" stop="1544704132424">
      <name>test_login</name>
      <failure>
        <message>failed</message>
        <stack-trace>test_login.py:17: in &lt;module&gt;
    print(get_data())
test_login.py:14: in get_data
    for data in ReadLoginYaml("data_login.yaml").read_login_yaml().values():
..\base\base_read_data.py:10: in read_login_yaml
    with open(self.failname, "r", encoding="utf-8") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'E:\\上课资料\\13.移动端\\PYTEST练习\\scripts\\data\\data_login.yaml'</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
